
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import * as path from 'path';
import { defineConfig, env } from "prisma/config";

// Charge le fichier .env depuis la racine du monorepo
dotenv.config({ path: path.join(__dirname, '../.env') });

const buildDatabaseUrl = () => {
  const user = process.env.POSTGRES_USER;
  const password = process.env.POSTGRES_PASSWORD ? encodeURIComponent(process.env.POSTGRES_PASSWORD) : '';
  const host = 'localhost';
  const port = process.env.POSTGRES_PORT;
  const db = process.env.POSTGRES_DB;
  return `postgresql://${user}:${password}@${host}:${port}/${db}?schema=public`;
};

// Injecte l'URL construite dans les variables d'environnement pour que le schema.prisma puisse la lire
process.env.DATABASE_URL = buildDatabaseUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
